apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-datastore
  namespace: automation
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 100Mi
