
name: bwees

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

volumes:
  nas-media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.188,nolock,soft,rw"
      device: ":/mnt/main/homelab/media"



services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api=true"
      - "--api.dashboard=true"

      - "--metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_backend"

      - "--providers.file=true"
      - "--providers.file.directory=/fileprovider"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.jellyweb.address=:7500"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

    ports:
      - 80:80
      - 7500:7500
      - 443:443

    labels:

      - "traefik.http.middlewares.redirecthttps.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirecthttps.redirectScheme.permanent=true"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"

      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      - "traefik.http.routers.traefik.rule=Host(`traefik.bwees.lab`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik,redirecthttps"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/storage/traefik/dynamic:/fileprovider
      - /home/bwees/storage/traefik/certs:/etc/traefik/certs:ro
    networks:
      - traefik_backend

    restart: unless-stopped

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    volumes:
      - /home/bwees/storage/changedetection:/datastore
    networks:
      - traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"

      - "traefik.http.routers.changedetection.rule=Host(`changedetection.bwees.lab`)"
      - "traefik.http.routers.changedetection.service=changedetection"
      - "traefik.http.routers.changedetection.entrypoints=web,websecure"

      - "traefik.http.routers.changedetection.middlewares=redirecthttps"

    environment:
      PLAYWRIGHT_DRIVER_URL: "ws://sockpuppetbrowser:3000"
    restart: unless-stopped

  sockpuppetbrowser:
    image: 'dgtlmoon/sockpuppetbrowser:latest'
    shm_size: 2g
    environment:
      DEFAULT_LAUNCH_ARGS: "[\"--window-size=1920,1080\"]"
    networks:
      - traefik_backend
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - traefik_backend
    volumes:
      - /home/bwees/storage/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.git.loadbalancer.server.port=3000"

      - "traefik.http.routers.git.rule=Host(`git.bwees.io`)"
      - "traefik.http.routers.git.service=git"
      - "traefik.http.routers.git.entrypoints=web,websecure"

      - "traefik.http.routers.git.middlewares=redirecthttps"


    restart: unless-stopped

  cah:
    image: ghcr.io/bwees/cah-discord:latest
    volumes:
      - /home/bwees/storage/cah:/etc/app/cards
    environment:
      - TOKEN=${CAH_TOKEN}
    networks:
      - traefik_backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - traefik_backend
    restart: unless-stopped

  node-red:
    image: ghcr.io/bwees/nodered-ffmpeg:latest
    environment:
      - TZ=America/New_York
    networks:
      - traefik_backend
    volumes:
      - /home/bwees/storage/nodered:/data
      - /home/bwees/storage/podcasts:/static/podcasts
      - /home/bwees/storage/ytdl/wan:/ytdl/wan
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"

      - "traefik.http.routers.nodered.rule=Host(`nodered.bwees.lab`)"
      - "traefik.http.routers.nodered.service=nodered"
      - "traefik.http.routers.nodered.entrypoints=web,websecure"

      - "traefik.http.routers.nodered.middlewares=redirecthttps"
    restart: unless-stopped
#    entrypoint: "npm start -- --userDir /data --safe"

  youtube-dl:
    image: "ghcr.io/alexta69/metube"
    volumes:
      - type: volume
        source: nas-media
        target: /downloads
        volume:
          subpath: ytdl
    environment:
      TEMP_DIR: "/tmp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ytdl.loadbalancer.server.port=8081"

      - "traefik.http.routers.ytdl.rule=Host(`ytdl.bwees.lab`)"
      - "traefik.http.routers.ytdl.service=ytdl"
      - "traefik.http.routers.ytdl.entrypoints=web,websecure"

      - "traefik.http.routers.ytdl-public.rule=Host(`ytdl.bwees.io`)"
      - "traefik.http.routers.ytdl-public.service=ytdl"
      - "traefik.http.routers.ytdl-public.entrypoints=web,websecure"

    networks:
      - traefik_backend
    restart: unless-stopped

  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    volumes:
      - /home/bwees/storage/spoolman:/home/app/.local/share/spoolman
    environment:
      - TZ=America/Chicago
    networks:
      - traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.spoolman.loadbalancer.server.port=8000"

      - "traefik.http.routers.spoolman.rule=Host(`spoolman.bwees.lab`)"
      - "traefik.http.routers.spoolman.service=spoolman"
      - "traefik.http.routers.spoolman.entrypoints=web,websecure"
    restart: unless-stopped

  actual-server:
      image: actualbudget/actual-server:latest
      volumes:
          - /home/bwees/storage/actual:/data
      ports:
          - 5006:5006
      networks:
        - traefik_backend
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.actual.loadbalancer.server.port=5006"

        - "traefik.http.routers.actual.rule=Host(`finance.bwees.lab`)"
        - "traefik.http.routers.actual.service=actual"
        - "traefik.http.routers.actual.entrypoints=web,websecure"
      restart: unless-stopped

