name: bwees

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

volumes:
  nas-gitea:
    driver: local
    driver_opts:
      type: 'nfs'
      o: 'addr=nas.bwees.lab,nolock,soft,rw'
      device: ':/mnt/main/homelab/gitea'

services:
  traefik:
    image: traefik:v3.6.6
    ports:
      - 80:80
      - 443:443
    command:
      - '--configFile=/etc/traefik/config/config.yml'
    labels:
      # Dashboard
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'

      - 'traefik.http.routers.traefik.rule=Host(`traefik.bwees.lab`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=web,websecure'
      - 'traefik.http.routers.traefik.middlewares=authtraefik'
      - 'traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/config/traefik:/etc/traefik/config
      - /storage/traefik/certs:/etc/traefik/certs:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.52.4
    volumes:
      - /storage/changedetection:/datastore
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.changedetection.loadbalancer.server.port=5000'

      - 'traefik.http.routers.changedetection.rule=Host(`changedetection.bwees.lab`)'
      - 'traefik.http.routers.changedetection.service=changedetection'
      - 'traefik.http.routers.changedetection.entrypoints=web,websecure'
    environment:
      PLAYWRIGHT_DRIVER_URL: 'ws://sockpuppetbrowser:3000'
    restart: unless-stopped

  sockpuppetbrowser:
    image: dgtlmoon/sockpuppetbrowser:0.0.3
    shm_size: 2g
    environment:
      DEFAULT_LAUNCH_ARGS: '["--window-size=1920,1080"]'
    networks:
      - traefik_backend
    restart: unless-stopped

  gitea:
    image: gitea/gitea:1.25
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - traefik_backend
    volumes:
      - nas-gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.git.loadbalancer.server.port=3000'

      - 'traefik.http.routers.git.rule=Host(`git.bwees.lab`)'
      - 'traefik.http.routers.git.service=git'
      - 'traefik.http.routers.git.entrypoints=web,websecure'
    restart: unless-stopped

  gitea-mirror:
    image: ghcr.io/raylabshq/gitea-mirror:v3.9.2
    restart: unless-stopped
    user: '1000:1000'
    volumes:
      - /storage/gitea-mirror:/app/data
    networks:
      - traefik_backend
    environment:
      - BETTER_AUTH_SECRET=${GITEA_MIRROR_AUTH_SECRET}
      - BETTER_AUTH_URL=https://gitea-mirror.bwees.lab
      - BETTER_AUTH_TRUSTED_ORIGINS=https://gitea-mirror.bwees.lab
      - NODE_ENV=production
      - DATABASE_URL=file:data/gitea-mirror.db
      - HOST=0.0.0.0
      - PORT=4321
      - PUBLIC_BETTER_AUTH_URL=https://gitea-mirror.bwees.lab
      - MIRROR_ISSUE_CONCURRENCY=1
      - MIRROR_PULL_REQUEST_CONCURRENCY=1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.gitea-mirror.loadbalancer.server.port=4321'

      - 'traefik.http.routers.gitea-mirror.rule=Host(`gitea-mirror.bwees.lab`)'
      - 'traefik.http.routers.gitea-mirror.service=gitea-mirror'
      - 'traefik.http.routers.gitea-mirror.entrypoints=web,websecure'

  cah:
    image: ghcr.io/bwees/cah-discord:latest
    volumes:
      - /storage/cah:/etc/app/cards
    environment:
      - TOKEN=${CAH_TOKEN}
    networks:
      - traefik_backend
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:2.4.1
    restart: unless-stopped
    volumes:
      - /storage/n8n:/home/node/.n8n
      - /storage/n8n/runner:/home/node/.n8n-files
    networks:
      - traefik_backend
    environment:
      - TZ=America/Chicago
      - WEBHOOK_URL=https://n8n.bwees.io
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNER_SECRET}
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_RUNNERS_TASK_TIMEOUT=3600
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=24
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      - NODES_EXCLUDE="[]"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.n8n.loadbalancer.server.port=5678'
      - 'traefik.http.routers.n8n.rule=Host(`n8n.bwees.lab`) || Host(`n8n.bwees.io`)'
      - 'traefik.http.routers.n8n.service=n8n'
      - 'traefik.http.routers.n8n.entrypoints=web,websecure'

  n8n-runner:
    image: ghcr.io/bwees/homelab/n8n-runner:latest
    restart: unless-stopped
    pull_policy: always
    networks:
      - traefik_backend
    environment:
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNER_SECRET}
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_TASK_TIMEOUT=3600
    volumes:
      - /storage/n8n/runner:/home/runner/.n8n-files

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.18.2
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
