name: immich-retro

volumes:
  model-cache:

networks:
  bwees_traefik_backend:
    external: true
  backend:

services:
  immich-server:
    image: registry.zackpollard.pro/immich-server:2.0.0
    volumes:
      - /storage/immich-retro/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - bwees_traefik_backend
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.imretro.loadbalancer.server.port=2283'
      - 'traefik.http.routers.imretro.rule=Host(`imretro.bwees.lab`) || Host(`imretro.bwees.io`)'
      - 'traefik.http.routers.imretro.service=imretro'
      - 'traefik.http.routers.imretro.entrypoints=web,websecure'
      - 'traefik.docker.network=bwees_traefik_backend'

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.144.1
    volumes:
      - model-cache:/cache
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - backend
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /storage/immich-retro/postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
