

name: immich

volumes:
  model-cache:
  nas:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas.bwees.lab,nolock,soft,rw"
      device: ":/mnt/main/homelab/media/immich-lib"

networks:
  bwees_traefik_backend:
    external: true
  backend:

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.137.1
    volumes:
      - nas:/data
      - /etc/localtime:/etc/localtime:ro
    user: 1000:1000
    environment:
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - bwees_traefik_backend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.routers.immich.rule=Host(`immich.bwees.lab`) || Host(`immich.bwees.io`)"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.routers.immich.entrypoints=web,websecure"
      - "traefik.docker.network=bwees_traefik_backend"

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.137.1
    volumes:
      - model-cache:/cache
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - backend
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /storage/immich:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
