name: media

networks:
  bwees_traefik_backend:
    external: true

volumes:
  nas-media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas.bwees.lab,nolock,soft,rw"
      device: ":/mnt/main/homelab/media"

#
# NFS Subdirectory Mounts
#
x-nas-media-tv: &nas-media-tv
  type: volume
  source: nas-media
  target: /tv
  volume:
    subpath: tv
    
x-nas-media-movies: &nas-media-movies
  type: volume
  source: nas-media
  target: /movies
  volume:
    subpath: movies

x-nas-tdarr-cache: &nas-tdarr-cache
  type: volume
  source: nas-media
  target: /temp
  volume:
    subpath: tdarr-cache

services:

  # Tailscale Exit Node Router
  # used for getting container traffic to linode exit node
  # cursed fact: you must subnet route on the host at least one time for this to work
  exitnode:
    image: tailscale/tailscale:v1.84.2
    hostname: media_stack
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "tailscale status"]
      interval: 1s
      timeout: 5s
      retries: 60
    environment:
      - TZ=America/Chicago
      - TS_EXTRA_ARGS=--reset --exit-node=100.109.20.66 --exit-node-allow-lan-access=true 
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=false
      - TS_USERSPACE=false
      - TS_TAILSCALED_EXTRA_ARGS=--tun=tailscale0
    volumes:
      - /storage/media/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - bwees_traefik_backend
    cap_add:
      - net_admin
      - sys_module
    dns:
      - 100.109.20.66
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.bittorrent.rule=Host(`bittorrent.bwees.lab`)"
      - "traefik.http.routers.bittorrent.service=bittorrent"
      - "traefik.http.routers.bittorrent.entrypoints=web,websecure"

      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.rule=Host(`radarr.bwees.lab`)"
      - "traefik.http.routers.radarr.service=radarr"
      - "traefik.http.routers.radarr.entrypoints=web,websecure"

      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.bwees.lab`)"
      - "traefik.http.routers.sonarr.service=sonarr"
      - "traefik.http.routers.sonarr.entrypoints=web,websecure"

      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.jackett.rule=Host(`jackett.bwees.lab`)"
      - "traefik.http.routers.jackett.service=jackett"
      - "traefik.http.routers.jackett.entrypoints=web,websecure"

  qbittorrent:
    image: linuxserver/qbittorrent:5.1.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=8080
    volumes:
      - /storage/media/qbittorrent:/config
      - /storage/media/downloads:/downloads
    network_mode: service:exitnode
    depends_on:
      - exitnode
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.10.7
    volumes:
      - /storage/media/jellyfin:/config
      - <<: *nas-media-tv
      - <<: *nas-media-movies

    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.bwees.lab
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    networks:
      - bwees_traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.bwees.lab`) || Host(`jellyfin.bwees.io`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=web,websecure"
    devices:
      - "/dev/dri:/dev/dri"

    restart: unless-stopped
  
  ###########
  ## ARR Apps
  ###########

  radarr:
    image: linuxserver/radarr:5.25.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /storage/media/radarr:/config
      - /storage/media/downloads:/downloads
      - <<: *nas-media-movies
    network_mode: service:exitnode
    depends_on:
      - exitnode
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.14
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /storage/media/sonarr:/config
      - /storage/media/downloads:/downloads
      - <<: *nas-media-tv
    network_mode: service:exitnode
    depends_on:
      - exitnode
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett:0.22.2008
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /storage/media/jackett/config:/config
    network_mode: service:exitnode
    depends_on:
      - exitnode
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:2.6.0
    environment:
      - TZ=America/Chicago
      - PORT=5055
    volumes:
      - /storage/media/jellyseer:/app/config
    restart: unless-stopped
    networks:
      - bwees_traefik_backend

    labels:
      - "traefik.enable=true"

      - "traefik.http.services.jellyseer.loadbalancer.server.port=5055"
      - "traefik.http.routers.jellyseer.rule=Host(`jellyseer.bwees.lab`)"
      - "traefik.http.routers.jellyseer.service=jellyseer"
      - "traefik.http.routers.jellyseer.entrypoints=web,websecure"

  tdarr:
    image: ghcr.io/haveagitgat/tdarr:2.43.01
    restart: unless-stopped
    networks:
      - bwees_traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tdarr.loadbalancer.server.port=8265"

      - "traefik.http.routers.tdarr.rule=Host(`tdarr.bwees.lab`)"
      - "traefik.http.routers.tdarr.service=tdarr"
      - "traefik.http.routers.tdarr.entrypoints=web,websecure"
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=homelab-bwees
    volumes:
      - /storage/media/tdarr/server:/app/server
      - /storage/media/tdarr/configs:/app/configs
      - /storage/media/tdarr/logs:/app/logs

      # Libraries
      - <<: *nas-media-tv
      - <<: *nas-media-movies
      - <<: *nas-tdarr-cache
    ports:
      - 8266:8266
    devices:
      - /dev/dri:/dev/dri
