apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wakapi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: wakapi-secret
    template:
      data:
        WAKAPI_PASSWORD_SALT: "{{ .password_salt }}"
  dataFrom:
    - extract:
        key: wakapi
