apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wakapi-data
  namespace: misc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 5Gi
