all:
  children:
    home:
      hosts:
        homelab-home:
          ansible_ssh_user: bwees
      vars:
        deploy_source: home

    router:
      hosts:
        homelab-router:
          ansible_ssh_user: root

    stepien:
      hosts:
        stepien-server:
          ansible_ssh_user: bwees
      vars:
        deploy_source: stepien
