apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel-data
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 1Gi
