name: linode

services:
  traefik:
    image: traefik:v3.5.3
    ports:
      - 100.109.20.66:80:80
      - 100.109.20.66:443:443
      - 96.126.113.207:80:81
      - 96.126.113.207:443:444
    command:
      - '--configFile=/etc/traefik/config.yml'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/traefik/certs:/etc/traefik/certs:ro
      - /storage/traefik/acme.json:/etc/traefik/acme.json
      - /home/bwees/deploy/traefik/dynamic:/dynamic
      - /home/bwees/deploy/traefik/config.yml:/etc/traefik/config.yml:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  uptimekuma:
    image: louislam/uptime-kuma:2.0.1
    volumes:
      - /storage/uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/ca-certificates:/certs:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/certs/bwees-ca.crt
    entrypoint: 'node server/server.js'
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.uptimekuma.loadbalancer.server.port=3001'

      - 'traefik.http.routers.uptimekuma.rule=Host(`kuma.bwees.lab`)'
      - 'traefik.http.routers.uptimekuma.service=uptimekuma'
      - 'traefik.http.routers.uptimekuma.entrypoints=privatesecure'
      - 'traefik.http.routers.uptimekuma.tls=true'

    restart: unless-stopped

  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    ports:
      - 100.109.20.66:53:53/udp
      - 100.109.20.66:53:53/tcp
    volumes:
      - /home/bwees/deploy/dns:/etc/bind
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.35.0
    volumes:
      - /storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_backend
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

      - 'traefik.http.routers.portainer.rule=Host(`lab.bwees.io`)'
      - 'traefik.http.routers.portainer.service=portainer'
      - 'traefik.http.routers.portainer.entrypoints=publicsecure'
      - 'traefik.http.routers.portainer.tls=true'

  beszel:
    image: henrygd/beszel:0.14.1
    restart: unless-stopped
    volumes:
      - /storage/beszel:/beszel_data
    networks:
      - traefik_backend
    environment:
      - BESZEL_HUB_APP_URL=https://beszel.bwees.lab
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.beszel.loadbalancer.server.port=8090'

      - 'traefik.http.routers.beszel.rule=Host(`beszel.bwees.lab`)'
      - 'traefik.http.routers.beszel.service=beszel'
      - 'traefik.http.routers.beszel.entrypoints=privatesecure'
      - 'traefik.http.routers.beszel.tls=true'

  derp:
    image: ghcr.io/fredliang44/derper:v1.88.3
    restart: unless-stopped
    environment:
      DERP_DOMAIN: derp.bwees.io
      DERP_VERIFY_CLIENTS: "true"
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /app/certs:/storage/derp
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.tcp.services.derp-tls.loadbalancer.server.port=443'

      - 'traefik.tcp.routers.derp-tls.rule=HostSNI(`derp.bwees.io`)'
      - 'traefik.tcp.routers.derp-tls.service=derp-tls'
      - 'traefik.tcp.routers.derp-tls.entrypoints=publicsecure'
      - 'traefik.tcp.routers.derp-tls.tls.passthrough=true'

      - 'traefik.http.services.derp-http.loadbalancer.server.port=80'

      - 'traefik.http.routers.derp.rule=Host(`derp.bwees.io`)'
      - 'traefik.http.routers.derp.service=derp-http'
      - 'traefik.http.routers.derp.entrypoints=public'
      - 'traefik.http.routers.derp.priority=110000'

    ports:
      - "96.126.113.207:3478:3478/udp"

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24
