name: linode

services:
  traefik:
    image: traefik:v3.6.2
    ports:
      - 100.109.20.66:80:80
      - 100.109.20.66:443:443
      - 45.79.9.235:80:81
      - 45.79.9.235:443:444
    command:
      - '--configFile=/etc/traefik/config.yml'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /storage/traefik/certs:/etc/traefik/certs:ro
      - /storage/traefik/acme.json:/etc/traefik/acme.json
      - /home/bwees/deploy/config/traefik/dynamic:/dynamic
      - /home/bwees/deploy/config/traefik/config.yml:/etc/traefik/config.yml:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  gatus:
    image: ghcr.io/twin/gatus:v5.33.0
    volumes:
      - /home/bwees/deploy/config/gatus:/config
      - /storage/gatus:/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      - GATUS_CONFIG_PATH=/config
      - GATUS_DISCORD_WEBHOOK=${GATUS_DISCORD_WEBHOOK}
    networks:
      - traefik_backend
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.gatus.loadbalancer.server.port=8080'
      - 'traefik.http.routers.gatus.rule=Host(`status.bwees.lab`)'
      - 'traefik.http.routers.gatus.service=gatus'
      - 'traefik.http.routers.gatus.entrypoints=privatesecure'

  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    ports:
      - 100.109.20.66:53:53/udp
      - 100.109.20.66:53:53/tcp
    volumes:
      - /home/bwees/deploy/config/dns:/etc/bind
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.36.0
    volumes:
      - /storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_backend
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

      - 'traefik.http.routers.portainer.rule=Host(`lab.bwees.io`)'
      - 'traefik.http.routers.portainer.service=portainer'
      - 'traefik.http.routers.portainer.entrypoints=publicsecure'

  beszel:
    image: henrygd/beszel:0.16.1
    restart: unless-stopped
    volumes:
      - /storage/beszel:/beszel_data
    networks:
      - traefik_backend
    environment:
      - BESZEL_HUB_APP_URL=https://beszel.bwees.lab
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.beszel.loadbalancer.server.port=8090'

      - 'traefik.http.routers.beszel.rule=Host(`beszel.bwees.lab`)'
      - 'traefik.http.routers.beszel.service=beszel'
      - 'traefik.http.routers.beszel.entrypoints=privatesecure'

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.16.1
    ports:
      - 45876:45876
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24
