apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: tailscale
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: tailscale/tailscale
              tag: 'v1.98.4'
            env:
              TZ: America/Chicago
              TS_USERSPACE: 'true'
              TS_SOCKS5_SERVER: '0.0.0.0:1055'
              TS_EXTRA_ARGS: '--reset --exit-node=100.105.77.106 --exit-node-allow-lan-access=true --hostname=media-stack'
              TS_STATE_DIR: /var/lib/tailscale
              TS_KUBE_SECRET: ''
              TS_ACCEPT_DNS: 'false'
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      main:
        controller: main
        ports:
          socks5:
            port: 1055

    persistence:
      state:
        existingClaim: tailscale-state
        globalMounts:
          - path: /var/lib/tailscale
