apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
spec:
  interval: 1h
  path: ./kubernetes/apps/hail-mary/media/seerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: miroir-config
      namespace: storage
    - name: volsync
      namespace: storage
    - name: onepassword
      namespace: secrets
  components:
    - ../../../../../components/volsync
  postBuild:
    substitute:
      APP: seerr
      VOLSYNC_CLAIM: seerr-config
  targetNamespace: media
