---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: dfp-backend-tuning
  namespace: networking
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-dfp
  http2:
    initialStreamWindowSize: 32Mi
    initialConnectionWindowSize: 64Mi
  connection:
    bufferLimit: 32Mi
