---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: dfp-http2-window-sizes
  namespace: networking
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-dfp
  tls:
    alpnProtocols:
      - http/1.1
