apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crosshatch
spec:
  interval: 1h
  path: ./kubernetes/apps/hail-mary/misc/crosshatch/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
    - name: onepassword
      namespace: secrets
  components:
    - ../../../../../components/volsync
  postBuild:
    substitute:
      APP: crosshatch
      VOLSYNC_CLAIM: crosshatch-data
  targetNamespace: misc
