---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ../../../../base/networking/tailscale-operator/proxies
  - ./proxyclass.yaml
patches:
  # advertise static endpoints (VPS ExternalIP:nodePort) for direct connections
  - target:
      kind: ProxyGroup
      name: .*-ingress
    patch: |-
      - op: add
        path: /spec/proxyClass
        value: tau-ceti-static-endpoints
