---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  volumeName: immich-ml-cache
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 1Ti