apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-data
  namespace: networking
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 256Mi
