---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-restic-b2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-restic-b2
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .repository }}/${CLUSTER}/${APP}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .keyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .applicationKey }}"
  data:
    - secretKey: repository
      remoteRef:
        key: restic-b2
        property: repository
    - secretKey: resticPassword
      remoteRef:
        key: restic-b2
        property: repo_password
    - secretKey: keyId
      remoteRef:
        key: restic-b2
        property: key_id
    - secretKey: applicationKey
      remoteRef:
        key: restic-b2
        property: application_key
        
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-restic-nas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-restic-nas
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "rest:http://{{ .restUsername }}:{{ .restPassword }}@${VOLSYNC_NAS_ENDPOINT:=nas.bwees.lab:8000}/${CLUSTER}/${APP}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: restic-nas
        property: restic-password
    - secretKey: username
      remoteRef:
        key: restic-nas
        property: rest-username
    - secretKey: credential
      remoteRef:
        key: restic-nas
        property: repo_password
