apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token
    template:
      data:
        token: '{{ .${CLUSTER} }}'
  dataFrom:
    - extract:
        key: flux-webhooks
