---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-dfp
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: false
  dependsOn:
    - name: envoy-gateway
    - name: bind9
    - name: cert-manager-issuers
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./kubernetes/apps/tau-ceti/networking/envoy-dfp/app
