apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        CLOUDFLARE_TUNNEL_ID: "{{ (b64dec .lab.CF_TUNNEL_TOKEN | fromJson).t }}"
        TUNNEL_TOKEN: "{{ .lab.CF_TUNNEL_TOKEN }}"
  
  dataFrom:
    - extract:
        key: cloudflare
