
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-hostpath   # dynamically provisioned by local-csi (democratic-csi)
  resources:
    requests:
      storage: 20Gi
