apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: browser-secret
    template:
      data:
        CUSTOM_USER: '{{ .username }}'
        PASSWORD: '{{ .password }}'
  dataFrom:
    - extract:
        key: browser
