apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pinchflat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pinchflat-secret
    template:
      data:
        BASIC_AUTH_USERNAME: '{{ .username }}'
        BASIC_AUTH_PASSWORD: '{{ .password }}'
  dataFrom:
    - extract:
        key: pinchflat
