apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crosshatch
spec:
  interval: 1h
  path: ./kubernetes/apps/lab/misc/crosshatch/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: democratic-csi
      namespace: storage
  targetNamespace: misc
