name: home

services:
  traefik:
    image: traefik:v3.6.0
    ports:
      - 80:80
      - 443:443
    command:
      - '--configFile=/etc/traefik/config.yml'
    labels:
      # Dashboard
      - 'traefik.enable=true'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'

      - 'traefik.http.routers.traefik.rule=Host(`traefik.bwees.home`)'
      - 'traefik.http.routers.traefik.service=api@internal'
      - 'traefik.http.routers.traefik.entrypoints=web'
      - 'traefik.http.routers.traefik.middlewares=authtraefik'
      - 'traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/traefik/dynamic:/dynamic
      - /home/bwees/deploy/traefik/config.yml:/etc/traefik/config.yml:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    volumes:
      - /home/bwees/deploy/dns:/etc/bind
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.11.2
    volumes:
      - /home/bwees/storage/jellyfin:/config
      - /home/bwees/nas-media:/media-library:ro
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.bwees.home
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.jellyfin.loadbalancer.server.port=8096'

      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.bwees.home`)'
      - 'traefik.http.routers.jellyfin.service=jellyfin'
      - 'traefik.http.routers.jellyfin.entrypoints=web'
    devices:
      - '/dev/dri:/dev/dri'
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/bwees/storage/hass:/config
    network_mode: host
    environment:
      TZ: America/New_York
    restart: unless-stopped

  photoframe:
    image: ghcr.io/bwees/photoframe:latest
    volumes:
      - /home/bwees/storage/photoframe:/app/static/images
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.photoframe.loadbalancer.server.port=8000'

      - 'traefik.http.routers.photoframe.rule=Host(`frame.bwees.home`)'
      - 'traefik.http.routers.photoframe.service=photoframe'
      - 'traefik.http.routers.photoframe.entrypoints=web'
    restart: unless-stopped

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.15.4
    ports:
      - 45876:45876
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
