name: home

services:
  traefik:
    image: traefik:v3.3.5
    command:
      - "--api=true"
      - "--api.dashboard=true"

      - "--metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_backend"

      - "--providers.file=true"
      - "--providers.file.directory=/fileprovider"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"

    ports:
      - 80:80
      - 443:443
  
    labels:
      # Dashboard
      - "traefik.enable=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

      - "traefik.http.routers.traefik.rule=Host(`traefik.bwees.home`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/storage/traefik/route_files:/fileprovider
    networks:
      - traefik_backend
    restart: unless-stopped

  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - /home/bwees/storage/bind:/etc/bind
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2025.2.1
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - traefik_backend
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    volumes:
      - /home/bwees/storage/jellyfin:/config
      - /home/bwees/nas-media:/media-library:ro
      - /home/bwees/storage/transmission/downloads/jellyfin:/transmission:ro
    environment:
      - JELLYFIN_PublishedServerUrl=jellyfin.bwees.home
    networks:
      - traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.bwees.home`)"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=web"
    devices:
      - "/dev/dri:/dev/dri"
    restart: unless-stopped

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /home/bwees/storage/hass:/config
    network_mode: host
    environment:
      TZ: America/New_York
    restart: unless-stopped

  photoframe:
    image: ghcr.io/bwees/photoframe:latest
    volumes:
      - /home/bwees/storage/photoframe:/app/static/images
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.photoframe.loadbalancer.server.port=8000"

      - "traefik.http.routers.photoframe.rule=Host(`frame.bwees.home`)"
      - "traefik.http.routers.photoframe.service=photoframe"
      - "traefik.http.routers.photoframe.entrypoints=web"
    restart: unless-stopped

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
