apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media
resources:
  - namespace.yaml
  - media-library/ks.yaml
  - tailscale/ks.yaml
  - qbittorrent/ks.yaml
  - jellyfin/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - prowlarr/ks.yaml
  - seerr/ks.yaml
  - tdarr/ks.yaml
  - flaresolverr/ks.yaml
  - shelfarr/ks.yaml
  - audiobookshelf/ks.yaml
