---
# Ingress for envoy-internal; replicas: 1 (tau-ceti is single-node, no HA).
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: tau-ceti-ingress
spec:
  type: ingress
  replicas: 1
