apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cah
spec:
  interval: 1h
  path: ./kubernetes/apps/lab/discord-bots/cah/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
    - name: onepassword
      namespace: external-secrets
  components:
    - ../../../../../components/volsync
  postBuild:
    substitute:
      APP: cah
      VOLSYNC_CLAIM: cah-cards
  targetNamespace: discord-bots
