apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        CLOUDFLARE_TUNNEL_ID: '{{ (b64dec .token | fromJson).t }}'
        TUNNEL_TOKEN: '{{ .token }}'

  dataFrom:
    - extract:
        key: cf-tunnel-${CLUSTER}
