apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config
  namespace: automation
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-runner-files
  namespace: automation
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
