endpoints:
  - name: eridani
    group: eridani
    url: 'icmp://100.101.55.71'
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: discord

  - name: immich
    group: eridani
    url: 'https://immich.home.bwees.dev/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: jellyfin
    group: eridani
    url: 'https://jellyfin.home.bwees.dev/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: photoframe
    group: eridani
    url: 'https://frame.home.bwees.dev/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord
