endpoints:
  # - name: nvr
  #   group: starforge
  #   url: 'https://cam.starforgefoundry.com/'
  #   interval: 1m
  #   conditions:
  #     - '[STATUS] == 200'
  #   alerts:
  #     - type: discord

  # - name: homeassistant
  #   group: starforge
  #   url: 'https://hass.starforgefoundry.com/'
  #   interval: 1m
  #   conditions:
  #     - '[STATUS] == 200'
  #   alerts:
  #     - type: discord

  - name: website
    group: starforge
    url: 'https://starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: orion
    group: starforge
    url: 'https://orion.starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord
