endpoints:
  - name: nvr
    group: starforge
    url: 'https://cam.starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: homeassistant
    group: starforge
    url: 'https://hass.starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: starforge-server
    group: starforge
    url: 'icmp://100.93.153.81'
    interval: 1m
    conditions:
      - '[CONNECTED] == true'
    alerts:
      - type: discord

  - name: website
    group: starforge
    url: 'https://starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 200'
    alerts:
      - type: discord

  - name: api
    group: starforge
    url: 'https://api.starforgefoundry.com/'
    interval: 1m
    conditions:
      - '[STATUS] == 404'
      - '[BODY].status == 404'
      - '[BODY].error == Not Found'
    alerts:
      - type: discord
