apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  interval: 1h
  path: ./kubernetes/apps/lab/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: volsync
      namespace: storage
    - name: onepassword
      namespace: external-secrets
    - name: media-library
    - name: intel-device-plugins
      namespace: operators
  components:
    - ../../../../../components/volsync
  postBuild:
    substitute:
      APP: jellyfin
      VOLSYNC_CLAIM: jellyfin-config
  targetNamespace: media
