apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-secret
    template:
      data:
        OPENROUTER_API_KEY: '{{ .openrouter_api_key }}'
        DISCORD_BOT_TOKEN: '{{ .discord_bot_token }}'
        HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: '{{ .dashboard_password }}'
        HERMES_DASHBOARD_BASIC_AUTH_SECRET: '{{ .dashboard_secret }}'

        NOTION_API_KEY: '{{ .notion_api_key }}'
  dataFrom:
    - extract:
        key: hermes
