apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mirror-data
  namespace: dev
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 100Mi
