apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cah
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cah-secret
    template:
      data:
        DISCORD_TOKEN: '{{ .token }}'
        DISCORD_APP_ID: '{{ .app_id }}'
  dataFrom:
    - extract:
        key: cah
