apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cah
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cah
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/bwees/cah-discord
              tag: 'v1.0.0'
            envFrom:
              - secretRef:
                  name: cah-secret
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 256Mi

    persistence:
      cards:
        existingClaim: cah-cards
        globalMounts:
          - path: /app/cards
