apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cah-cards
  namespace: discord-bots
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 100Mi
