apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-media-library
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  mountOptions:
    - nfsvers=4.1
    - nolock
    - soft
  nfs:
    server: nas.bwees.lab
    path: /media
