services:
  beszel-agent:
    container_name: beszel-agent
    environment:
      KEY: INSERT_KEY_HERE
      LISTEN: 45876
    image: henrygd/beszel-agent:0.10.2
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
