services:
  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.16.1
    ports:
      - 45876:45876
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  syncthing:
    image: syncthing/syncthing:2.0.11
    environment:
      - PUID=3000
      - PGID=3000
    volumes:
      - /mnt/main/homelab/syncthing:/var/syncthing
      - /mnt/main/personal/bwees:/nas/bwees/personal
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3

  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.90.9
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/main/homelab/nas-tailscale:/var/lib/tailscale
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_ACCEPT_DNS: 'false'
      TS_HOSTNAME: bwees-nas
    restart: unless-stopped

  locplace-scanner:
    image: ghcr.io/locplace/scanner:0.2.1
    pull_policy: always
    restart: unless-stopped
    environment:
      - COORDINATOR_URL=https://loc.place
      - SCANNER_TOKEN=${LOCPLACE_SCANNER_TOKEN}
