services:
  beszel-agent:
    container_name: beszel-agent
    environment:
      KEY: {{ secrets.other.BESZEL_KEY }}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.11.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  tdarr:
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=bwees-nas
      - serverIP=192.168.50.200
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
    image: haveagitgat/tdarr_node:2.45.01
    restart: unless-stopped
    volumes:
      - /mnt/main/homelab/media/tv:/tv
      - /mnt/main/homelab/media/movies:/movies
      - /mnt/main/homelab/media/tdarr-cache:/temp

  syncthing:
    image: syncthing/syncthing:1.30.0
    environment:
      - PUID=3000
      - PGID=3000
    volumes:
      - /mnt/main/homelab/syncthing:/var/syncthing
      - /mnt/main/personal/bwees:/nas/bwees/personal
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
