name: nas

services:
  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.17.0
    ports:
      - 45876:45876
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.92.4
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/main/homelab/nas-tailscale:/var/lib/tailscale
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_ACCEPT_DNS: 'false'
      TS_HOSTNAME: homelab-nas
    restart: unless-stopped
