services:
  tdarr:
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - nodeName=bwees-nas
      - serverIP=192.168.10.200
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
    image: haveagitgat/tdarr_node:2.36.01
    restart: unless-stopped
    volumes:
      - /mnt/main/homelab/media/tv:/tv
      - /mnt/main/homelab/media/movies:/movies
      - /mnt/main/homelab/media/tdarr-cache:/temp
