apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psitransfer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: psitransfer-secret
    template:
      data:
        PSITRANSFER_ADMIN_PASS: '{{ .admin_pass }}'
        PSITRANSFER_UPLOAD_PASS: '{{ .upload_pass }}'
  dataFrom:
    - extract:
        key: psitransfer
