apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zulu-notifyd-data
  namespace: misc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 256Mi
