apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: network

resources:
  - namespace.yaml
  - envoy-gateway/ks.yaml
  - cert-manager/ks.yaml
  - cloudflare-dns/ks.yaml
  - cloudflare-tunnel/ks.yaml
