apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    template:
      data:
        GATUS_DISCORD_WEBHOOK: '{{ .discord_webhook }}'
  dataFrom:
    - extract:
        key: gatus
