apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crosshatch-data
  namespace: misc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 100Mi
