apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-bind
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-rfc2136
    template:
      data:
        TSIG_SECRET: '{{ .password }}'
  dataFrom:
    - extract:
        key: bind9-tsig
