---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: futo-backups-data
  namespace: storage
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 10Gi
