- name: Configure Bind DNS Servers
  hosts: all
  gather_facts: false

  tasks:
    - name: Copy folder with DNS configuration files
      copy:
        src: "../../configs/dns/{{ stack_name }}/"
        dest: "{{ dns_folder }}"

    - name: Reload Bind9
      community.docker.docker_container:
        name: "{{ stack_name }}-bind9-1"
        restart: true
