- name: Install Beszel
  hosts: all
  gather_facts: false

  tasks:
    - name: Load secrets from Ansible Vault file
      include_vars:
        file: "../secrets.resolved.yml"
        name: secrets

    - name: Download Beszel Agent
      get_url:
        url: "https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh"
        dest: "/tmp/install-agent.sh"
        mode: '0755'

    - name: Install Beszel Agent
      raw: |
          echo -e "y\n" | bash /tmp/install-agent.sh -p 45876 -k "{{ secrets.other.BESZEL_KEY }}"
      register: beszel_install
      changed_when: beszel_install.rc != 0

    - name: Remove Beszel Agent installer
      file:
        path: "/tmp/install-agent.sh"
        state: absent
