- name: Update Tailscale with tailscale update
  hosts: all
  gather_facts: false
  tasks:
    - name: Update Tailscale
      block:
        - name: Run `tailscale update`
          command: tailscale update
          register: tailscale_update
          become: true
          changed_when: tailscale_update.stdout.find('no update needed') == -1
          failed_when: tailscale_update.rc != 0
