- name: Update Beszel
  hosts: all
  gather_facts: false

  tasks:
    - name: Download Beszel Agent
      raw: |
        /opt/beszel-agent/beszel-agent update
      register: beszel_update
      changed_when: beszel_update.rc != 0

    - name: Restart Beszel Agent Service
      service:
        name: beszel-agent
        state: restarted
