- name: Update Beszel
  hosts: all
  gather_facts: false

  tasks:
    - name: Download Beszel Agent
      raw: |
        sudo /opt/beszel-agent/beszel-agent update
        sudo service beszel-agent restart
      register: beszel_update
      changed_when: beszel_update.rc != 0
