---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      vault: Homelab Deployment
      auth:
        serviceAccountSecretRef:
          name: onepassword-secret-token
          key: token
          namespace: external-secrets
      integrationInfo:
        name: external-secrets
        version: v1.0.0
