---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: networking
spec:
  secretName: wildcard-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  dnsNames:
    - 'bwees.io'
    - '*.bwees.io'
    - 'wees.home'
    - '*.wees.home'
    - 'bwees.lab'
    - '*.bwees.lab'
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: bwees-ca
    kind: ClusterIssuer
    group: cert-manager.io
