---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-cert-manager
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-cert-manager
    template:
      data:
        api-token: '{{ .token }}'
  dataFrom:
    - extract:
        key: cf-cert-manager
