switch HOST USER="bwees":
  nixos-rebuild switch \
    --flake .#"{{HOST}}" \
    --target-host "{{USER}}@{{HOST}}" \
    --build-host "{{USER}}@{{HOST}}" \
    --sudo \
    --no-reexec

anywhere HOST IP USER="root":
  nix run github:nix-community/nixos-anywhere -- --flake .#"{{HOST}}" "{{USER}}@{{IP}}"