---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wees-home-tailnet
spec:
  endpoints:
    - dnsName: '*.wees.home'
      recordType: A
      targets:
        - 100.108.214.28 # svc:eridani-ingress (tailscale VIPService)
