apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: sonarr
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: '4.0.18.2978'
            env:
              TZ: America/Chicago
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8989
              readiness: *probes

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: 8989
            appProtocol: kubernetes.io/ws

    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: networking
        hostnames:
          - sonarr.bwees.lab
        rules:
          - backendRefs:
              - identifier: main
                port: 8989

    persistence:
      config:
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media-library
        globalMounts:
          - path: /tv
            subPath: tv
          - path: /downloads
            subPath: downloads
