apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: n8n
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: n8nio/n8n
              tag: "2.26.1"
            envFrom:
              - secretRef:
                  name: n8n-secret
            env:
              TZ: America/Chicago
              WEBHOOK_URL: https://n8n.bwees.io
              N8N_RUNNERS_ENABLED: "true"
              N8N_RUNNERS_MODE: external
              N8N_RUNNERS_BROKER_LISTEN_ADDRESS: 0.0.0.0
              N8N_NATIVE_PYTHON_RUNNER: "true"
              N8N_RUNNERS_TASK_TIMEOUT: "3600"
              EXECUTIONS_DATA_PRUNE: "true"
              EXECUTIONS_DATA_MAX_AGE: "24"
              EXECUTIONS_DATA_SAVE_ON_SUCCESS: none
              NODES_EXCLUDE: "[]"
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
          runner:
            image:
              repository: ghcr.io/bwees/homelab/n8n-runner
              tag: latest
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: n8n-secret
            env:
              N8N_RUNNERS_TASK_BROKER_URI: http://localhost:5679
              N8N_RUNNERS_TASK_TIMEOUT: "3600"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: 5678
            appProtocol: kubernetes.io/ws

    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
          - name: envoy-external
            namespace: network
        hostnames:
          - n8n.bwees.lab
          - n8n.bwees.io
        rules:
          - backendRefs:
              - identifier: main
                port: 5678

    persistence:
      config:
        existingClaim: n8n-config
        advancedMounts:
          main:
            main:
              - path: /home/node/.n8n
      runner-files:
        existingClaim: n8n-runner-files
        advancedMounts:
          main:
            main:
              - path: /home/node/.n8n-files
            runner:
              - path: /home/runner/.n8n-files
