name: stepien

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  traefik:
    image: traefik:v3.6.2
    command:
      - '--configFile=/etc/traefik/config.yml'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/config/traefik/config.yml:/etc/traefik/config.yml:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.16.1
    ports:
      - 45876:45876
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  locplace-scanner:
    image: ghcr.io/locplace/scanner:0.2.0
    pull_policy: always
    restart: unless-stopped
    environment:
      - COORDINATOR_URL=https://loc.place
      - SCANNER_TOKEN=${LOCPLACE_SCANNER_TOKEN}
