name: stepien

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  traefik:
    image: traefik:v3.5.3
    command:
      - '--configFile=/etc/traefik/config.yml'
    ports:
      - 80:80
      - 443:443      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/traefik/config.yml:/etc/traefik/config.yml:ro
    networks:
      - traefik_backend
    restart: unless-stopped