name: stepien

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24

services:
  traefik:
    image: traefik:v3.6.6
    command:
      - '--configFile=/etc/traefik/config/config.yml'
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/config/traefik:/etc/traefik/config
    networks:
      - traefik_backend
    restart: unless-stopped

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.18.1
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
