apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readme-stats
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: readme-stats-secret
    template:
      data:
        GITHUB_TOKEN: '{{ .credential }}'
  dataFrom:
    - extract:
        key: gh-readme-stats
