apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-api-token
    template:
      data:
        CF_API_TOKEN: '{{ .token }}'
        CF_ZONE_ID: '{{ .zone }}'

  dataFrom:
    - extract:
        key: cf-external-dns
