name: vps

services:
  traefik:
    image: traefik:v3.6.6
    ports:
      - 100.105.77.106:80:80
      - 100.105.77.106:443:443
      - 40.160.239.102:80:81
      - 40.160.239.102:443:444
    command:
      - '--configFile=/etc/traefik/config/config.yml'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/bwees/deploy/config/traefik:/etc/traefik/config
      - /storage/traefik/certs:/etc/traefik/certs:ro
    networks:
      - traefik_backend
    restart: unless-stopped

  gatus:
    image: ghcr.io/twin/gatus:v5.34.0
    volumes:
      - /home/bwees/deploy/config/gatus:/config
      - /storage/gatus:/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
    environment:
      - GATUS_CONFIG_PATH=/config
      - GATUS_DISCORD_WEBHOOK=${GATUS_DISCORD_WEBHOOK}
    networks:
      - traefik_backend
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.gatus.loadbalancer.server.port=8080'
      - 'traefik.http.routers.gatus.rule=Host(`status.bwees.lab`)'
      - 'traefik.http.routers.gatus.service=gatus'
      - 'traefik.http.routers.gatus.entrypoints=privatesecure'

  bind9:
    image: ubuntu/bind9:9.18-24.04_beta
    ports:
      - 100.105.77.106:53:53/udp
      - 100.105.77.106:53:53/tcp
    volumes:
      - /home/bwees/deploy/config/dns:/etc/bind
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.37.0
    volumes:
      - /storage/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_backend
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

      - 'traefik.http.routers.portainer.rule=Host(`lab.bwees.io`)'
      - 'traefik.http.routers.portainer.service=portainer'
      - 'traefik.http.routers.portainer.entrypoints=publicsecure'

  beszel:
    image: henrygd/beszel:0.18.2
    restart: unless-stopped
    volumes:
      - /storage/beszel:/beszel_data
    networks:
      - traefik_backend
    environment:
      - BESZEL_HUB_APP_URL=https://beszel.bwees.lab
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.beszel.loadbalancer.server.port=8090'

      - 'traefik.http.routers.beszel.rule=Host(`beszel.bwees.lab`)'
      - 'traefik.http.routers.beszel.service=beszel'
      - 'traefik.http.routers.beszel.entrypoints=privatesecure'

  beszel-agent:
    environment:
      KEY: ${BESZEL_KEY}
      LISTEN: 45876
    image: henrygd/beszel-agent:0.18.2
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  github-readme-stats-docker:
    image: crusaders/github-readme-stats-docker:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - GITHUB_USER=bwees
      - GITHUB_TOKEN=${GITHUB_STATS_TOKEN}
    networks:
      - traefik_backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.readmestats.loadbalancer.server.port=80'

      - 'traefik.http.routers.readmestats.rule=Host(`stats.bwees.io`)'
      - 'traefik.http.routers.readmestats.service=readmestats'
      - 'traefik.http.routers.readmestats.entrypoints=publicsecure'

networks:
  traefik_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24
