apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../lib/media/jellyfin
  - pvc.yaml

patches:
  - path: helmrelease.patch.yaml
    target:
      kind: HelmRelease
      name: jellyfin
