apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maroonrides-db-dumps
  namespace: maroonrides
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 2Gi
