apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: seerr
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: 'v3.3.0'
            env:
              TZ: America/Chicago
              PORT: '5055'
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes

    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      main:
        controller: main
        ports:
          http:
            port: 5055
            appProtocol: kubernetes.io/ws

    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: networking
        hostnames:
          - seerr.bwees.lab
        rules:
          - backendRefs:
              - identifier: main
                port: 5055

    persistence:
      config:
        existingClaim: seerr-config
        globalMounts:
          - path: /app/config
