apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir
  resources:
    requests:
      storage: 1Gi
