apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: "10.11.10"
            env:
              TZ: Europe/Amsterdam
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8096
              readiness: *probes
              
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
            appProtocol: kubernetes.io/ws
    route:
      main:
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - jellyfin.test.lab
        rules:
          - backendRefs:
              - identifier: main
                port: 8096
    persistence:
      config:
        existingClaim: jellyfin-config
        globalMounts:
          - path: /config
      tmpfs:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /transcode
                subPath: transcode