apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-cloudflare
    template:
      data:
        CF_API_TOKEN: '{{ .token }}'
  dataFrom:
    - extract:
        key: cf-external-dns
