apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/networking/envoy-gateway/config

patches:
  - target:
      kind: Gateway
      name: envoy-internal
    patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      metadata:
        name: envoy-internal
        annotations:
          external-dns.alpha.kubernetes.io/target: 100.100.100.100 # stepien-ingress tailnet IP
