---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bwees-ca
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: bwees-ca-key-pair
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: certificate-authority
        property: bwees-ca.crt
    - secretKey: tls.key
      remoteRef:
        key: certificate-authority
        property: bwees-ca.key
