- name: Load secrets from Ansible Vault file
  include_vars:
    file: "{{ vault_file }}"
    name: all_secrets_data

- name: Create .env content for the host
  template:
    src: secret_env.j2
    dest: "/tmp/{{ inventory_hostname }}.env"
    # set the permissions to 0600
    mode: '0600'
  delegate_to: localhost  # Generate locally before transfer

- name: Transfer the .env file to the host
  copy:
    src: "/tmp/{{ inventory_hostname }}.env"
    dest: "{{ env_destination }}"
    # set the permissions to 0600
    mode: '0600'
