- name: Generates a .env file from Ansible Vault and uploads it to the host
  block:
    - name: Load secrets from Ansible Vault file
      include_vars:
        file: "{{ vault_file }}"
        name: all_secrets_data

    - name: Create .env content for the host
      template:
        src: secret_env.j2
        dest: "/tmp/{{ inventory_hostname }}.env"
        # set the permissions to 0755
        mode: '0755'
      delegate_to: localhost  # Generate locally before transfer

    - name: Transfer the .env file to the host
      copy:
        src: "/tmp/{{ inventory_hostname }}.env"
        dest: "{{ env_destination }}"
        # set the permissions to 0755
        mode: '0755'
